docker_build_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  variables:
    DOCKER_REGISTRY: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  script:
    - /kaniko/executor \
      --context "${CI_PROJECT_DIR}" \
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
      --destination "${DOCKER_REGISTRY}"
