# Service to expose Apache reverse proxy
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: exercise02
spec:
  selector:
    app: apache-reverse-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
# Defines a deployment for the Apache reverse proxy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-reverse-proxy
  namespace: exercise02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-rev-prox
  template:
    metadata:
      labels:
        app: apache-rev-prox
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /dashboard/
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 15
      readinessProbe:
        httpGet:
          path: /dashboard/
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 15
        volumeMounts:
        - name: apache-config
          mountPath: /usr/local/apache2/conf/httpd.conf
          subPath: httpd.conf
      volumes:
      - name: apache-config
        configMap:
          name: apache-config
---
# ConfigMap to store Apache configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
  namespace: exercise02
data:
  httpd.conf: |
data:
  httpd.conf: |
    # Main server configuration
    ServerRoot "/usr/local/apache2"
    Listen 80

    # Required modules for reverse proxy functionality
    LoadModule unixd_module modules/mod_unixd.so
    LoadModule mpm_event_module modules/mod_mpm_event.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule log_config_module modules/mod_log_config.so
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_http_module modules/mod_proxy_http.so

    # Apache user and group settings
    User daemon
    Group daemon

    # Set ServerName to prevent DNS lookups
    ServerName localhost

    # Restrict access to the root directory
    <Directory />
        Require all denied
    </Directory>

    # Grant access to the document root directory
    <Directory "/usr/local/apache2/htdocs">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    # Reverse proxy rules for Beetroot API service
    ProxyRequests Off
    ProxyPass / http://beetroot-service.exercise02.svc.cluster.local:80/
    ProxyPassReverse / http://beetroot-service.exercise02.svc.cluster.local:80/

    # Redirect error and access logs to standard output streams
    ErrorLog /proc/self/fd/2
    LogLevel warn
    CustomLog /proc/self/fd/1 common


